import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "./api.js";

const button = { border: 0, borderRadius: 12, padding: "7px 10px", fontSize: 10.5, cursor: "pointer" };
const card = { marginTop: 10, padding: 12, border: "0.5px solid rgba(0,0,0,.09)", borderRadius: 14, background: "rgba(255,255,255,.7)" };
const anchorLabels = { people_places: "人名 / 地点", event_names: "事件名称", key_objects: "关键物品", special_phrases: "特殊表达", synonyms: "常见同义说法", final_state_terms: "最后状态" };

function Evidence({ items = [] }) {
  return <details><summary style={{ fontSize: 10, cursor: "pointer", color: "#6E6E73" }}>查看完整原文证据（{items.length}）</summary>{items.map((item, index) => <blockquote key={`${item.messageNumber}-${index}-${item.quote}`} style={{ margin: "5px 0", padding: "7px 9px", borderLeft: "2px solid #C7C7CC", fontSize: 10, lineHeight: 1.5, whiteSpace: "pre-wrap" }}><b>{item.experienceTitle ? `${item.experienceTitle} · ` : ""}M{item.messageNumber} · {item.role}</b><br />{item.quote}</blockquote>)}</details>;
}

function Workspace({ workspace, documents, busy, onAssign, onDistill, onMerge, onPatchReview }) {
  const available = documents.filter((document) => document.character_id === workspace.character_id);
  const assigned = workspace.notes.filter((note) => note.target_document_id);
  const targetCount = new Set(assigned.map((note) => note.target_document_id)).size;
  return <article style={card}>
    <b style={{ fontSize: 12 }}>{workspace.conversation_imports?.title}</b>
    <p style={{ fontSize: 10, color: "#636366" }}>已提取 {workspace.extractedSegmentCount} / {workspace.conversation_imports?.segment_count} 个片段 · 经历 {workspace.experienceCount || 0} 条 · MD 素材 {workspace.extractedNoteCount || 0} 条</p>
    <p style={{ fontSize: 9.5, color: "#AF7A28" }}>先积累有原文证据的经历；再把整份导入集中整理成少量 MD 素材。原始 MD 不会自动修改。</p>
    <button style={{ ...button, margin: "4px 0 8px", background: "#E9E4DA" }} disabled={busy || !(workspace.experienceCount > 0)} onClick={() => onDistill(workspace)}>{busy ? "整理中…" : "整理这份导入，生成 MD 素材"}</button>
    {!workspace.notes.length && <p style={{ fontSize: 10, color: "#8E8E93" }}>目前还没有 MD 素材。经历已经保存在下方；点击上面的按钮后，系统会综合多段经历再提出修改建议。</p>}
    {workspace.notes.map((note) => <section key={note.id} style={{ padding: "8px 0", borderTop: "0.5px solid rgba(0,0,0,.06)" }}><div style={{ fontSize: 10.5, whiteSpace: "pre-wrap" }}>{note.note_markdown}</div><div style={{ display: "flex", gap: 6, alignItems: "center", margin: "6px 0" }}><span style={{ fontSize: 9.5, color: "#8E8E93" }}>建议：{note.suggested_document_name}</span><select value={note.target_document_id || ""} disabled={busy} onChange={(event) => onAssign(note, event.target.value || null)} style={{ flex: 1, minWidth: 120, border: "0.5px solid rgba(0,0,0,.12)", borderRadius: 8, padding: 5, fontSize: 10 }}><option value="">留在素材箱，不加入文件</option>{available.map((document) => <option key={document.id} value={document.id}>{document.name}</option>)}</select></div><Evidence items={note.evidence_refs} /></section>)}
    <button style={{ ...button, marginTop: 8, background: "#1C1C1E", color: "#fff" }} disabled={busy || !assigned.length} onClick={() => onMerge(workspace, targetCount)}>{busy ? "逐份合并中…" : `按已有 MD 生成 ${targetCount} 份修改预览`}</button>
    {(workspace.patches || []).map((patch) => <section key={patch.id} style={{ marginTop: 10, padding: 10, borderRadius: 10, background: "rgba(52,199,89,.055)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><b style={{ fontSize: 11 }}>{patch.document_name}</b><span style={{ fontSize: 9.5, color: patch.review_status === "confirmed" ? "#248A3D" : patch.review_status === "rejected" ? "#C9342D" : "#AF7A28" }}>{patch.review_status === "confirmed" ? "已写入原文件" : patch.review_status === "rejected" ? "已拒绝" : "待确认"}</span></div><p style={{ fontSize: 10.5 }}>{patch.change_summary}</p><p style={{ fontSize: 9.5, color: "#636366" }}>采用 {patch.source_note_ids?.length || 0}/{patch.mention_count} 条素材，来自 {patch.segment_count} 个片段。合并理由：{patch.merge_reason}</p><details><summary style={{ fontSize: 10, cursor: "pointer" }}>修改前</summary><pre style={{ whiteSpace: "pre-wrap", maxHeight: 240, overflow: "auto", fontSize: 9.5 }}>{patch.previous_content}</pre></details><details><summary style={{ fontSize: 10, cursor: "pointer" }}>修改后</summary><pre style={{ whiteSpace: "pre-wrap", maxHeight: 300, overflow: "auto", fontSize: 9.5 }}>{patch.proposed_content}</pre></details>{patch.review_status === "suggested" && <div style={{ display: "flex", justifyContent: "flex-end", gap: 6, marginTop: 8 }}><button style={{ ...button, color: "#C9342D" }} disabled={busy} onClick={() => onPatchReview(patch, "reject")}>拒绝</button><button style={{ ...button, background: "#1C1C1E", color: "#fff" }} disabled={busy} onClick={() => onPatchReview(patch, "confirm")}>确认更新原 MD</button></div>}</section>)}
  </article>;
}

function BatchDetails({ batches }) {
  return <details style={{ marginTop: 12 }}><summary style={{ fontSize: 10.5, cursor: "pointer" }}>查看分片经历与证据（{batches.length} 批）</summary>{batches.map((batch) => <article key={batch.id} style={card}><div style={{ fontSize: 10, color: "#8E8E93" }}>片段 #{batch.imported_conversation_segments?.sequence} · {new Date(batch.imported_conversation_segments?.started_at).toLocaleString()}</div>{(batch.memory_experience_candidates || []).map((item) => <section key={item.id} style={{ padding: "8px 0", borderTop: "0.5px solid rgba(0,0,0,.06)" }}><b style={{ fontSize: 11 }}>{item.title}</b><div style={{ fontSize: 10.5, lineHeight: 1.6, whiteSpace: "pre-wrap", margin: "5px 0" }}>{item.narrative_markdown}</div><div style={{ display: "grid", gridTemplateColumns: "repeat(2,minmax(0,1fr))", gap: 5, margin: "7px 0" }}>{Object.entries(anchorLabels).map(([key, label]) => <div key={key} style={{ padding: 6, borderRadius: 8, background: "rgba(0,0,0,.025)", fontSize: 9.5 }}><b>{label}</b><br />{(item.search_anchors?.[key] || []).join("、") || "—"}</div>)}</div><Evidence items={item.evidence_refs} /></section>)}</article>)}</details>;
}

export default function MemoryPracticeSettings() {
  const [imports, setImports] = useState([]); const [segments, setSegments] = useState([]); const [selectedImportId, setSelectedImportId] = useState("");
  const [batches, setBatches] = useState([]); const [workspaces, setWorkspaces] = useState([]); const [documents, setDocuments] = useState([]); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const refresh = useCallback(async () => { const [batchData, workspaceData] = await Promise.all([api("/memory-practice/batches"), api("/memory-practice/workspaces")]); setBatches(batchData.batches || []); setWorkspaces(workspaceData.workspaces || []); setDocuments(workspaceData.documents || []); }, []);
  useEffect(() => { let active = true; Promise.all([api("/timeline-imports"), api("/memory-practice/batches"), api("/memory-practice/workspaces")]).then(([importsData, batchData, workspaceData]) => { if (!active) return; setImports(importsData.imports || []); setBatches(batchData.batches || []); setWorkspaces(workspaceData.workspaces || []); setDocuments(workspaceData.documents || []); }).catch((error) => { if (active) setMessage(error.message); }); return () => { active = false; }; }, []);
  const selectedWorkspace = useMemo(() => workspaces.find((item) => item.import_id === selectedImportId), [workspaces, selectedImportId]);
  async function openImport(item) { try { setBusy("imports"); const data = await api(`/timeline-imports/${item.id}/segments`); setSelectedImportId(item.id); setSegments(data.segments || []); setMessage("第一步提取片段；第二步集中整理整份导入；第三步检查归类并生成 MD 修改预览。"); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function extractOne(segment, ask = true) { if (ask && !window.confirm("这一步会调用便宜模型两次；某一步格式不合格时可能重试一次。继续吗？")) return false; try { setBusy(segment.id); setMessage(`正在提取片段 #${segment.sequence}…`); const result = await api(`/memory-practice/segments/${segment.id}/extract`, { method: "POST" }); await refresh(); setMessage(`片段 #${segment.sequence} 提取完成：${result.experiences?.length || 0} 条经历，${result.knowledgeNotes?.length || 0} 条 MD 素材。`); return true; } catch (error) { setMessage(error.message); return false; } finally { setBusy(""); } }
  async function extractFive() { const done = new Set(selectedWorkspace?.extractedSegmentIds || []); const pending = segments.filter((segment) => !done.has(segment.id)).slice(0, 5); if (!pending.length) return setMessage("这份导入当前没有未提取片段。"); if (!window.confirm(`将顺序处理 ${pending.length} 个片段，通常调用便宜模型 ${pending.length * 2} 次；格式错误时可能额外重试。继续吗？`)) return; for (const segment of pending) { const ok = await extractOne(segment, false); if (!ok) break; } await refresh(); }
  async function assign(note, targetDocumentId) { try { setBusy(note.id); await api(`/memory-practice/notes/${note.id}/target`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ targetDocumentId }) }); await refresh(); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function distill(workspace) { if (!window.confirm(`将综合目前 ${workspace.experienceCount || 0} 条有证据的经历，生成少量 MD 素材。经历较多时会分组调用整理模型；不会修改原文件。继续吗？`)) return; try { setBusy(workspace.id); setMessage("正在综合整份导入中的经历…"); const result = await api(`/memory-practice/workspaces/${workspace.id}/distill`, { method: "POST" }); await refresh(); setMessage(`集中整理完成：参考 ${result.experienceCount || 0} 条经历，生成 ${result.notes?.length || 0} 条 MD 素材。请检查归类后再生成修改预览。`); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function merge(workspace, targetCount) { if (!window.confirm(`将按文件顺序调用校验模型 ${targetCount} 次，每份已有 MD 单独处理。继续吗？`)) return; try { setBusy(workspace.id); setMessage("正在按已有 MD 逐份生成合并预览…"); await api(`/memory-practice/workspaces/${workspace.id}/merge`, { method: "POST" }); await refresh(); setMessage("合并预览已生成。原始 MD 尚未修改。"); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  async function reviewPatch(patch, action) { if (action === "confirm" && !window.confirm(`确认用“修改后”的内容更新《${patch.document_name}》吗？系统会保留旧版本。`)) return; try { setBusy(patch.id); await api(`/memory-practice/document-patches/${patch.id}/${action}`, { method: "POST" }); await refresh(); setMessage(action === "confirm" ? `《${patch.document_name}》已经更新，旧版本仍可追溯。` : `已拒绝《${patch.document_name}》的本次修改。`); } catch (error) { setMessage(error.message); } finally { setBusy(""); } }
  const selectedBatches = batches.filter((batch) => batch.workspace_id === selectedWorkspace?.id);
  return <div><p style={{ fontSize: 10.5, color: "#636366", lineHeight: 1.6 }}>按整次导入积累有原文证据的经历，再集中修改你已有的 Markdown。旧 Timeline 不会被修改。</p>{message && <p role="status" style={{ fontSize: 10.5, color: "#8E8E93", whiteSpace: "pre-wrap" }}>{message}</p>}
    {imports.map((item) => <button key={item.id} style={{ ...button, display: "block", width: "100%", textAlign: "left", marginTop: 5, background: selectedImportId === item.id ? "#E9E4DA" : undefined }} disabled={busy === "imports"} onClick={() => openImport(item)}>{item.title} · {item.message_count} 条 · {item.segment_count} 段</button>)}
    {!!segments.length && <><button style={{ ...button, marginTop: 8 }} disabled={!!busy} onClick={extractFive}>提取接下来最多 5 个片段</button><div style={{ maxHeight: 220, overflow: "auto", marginTop: 8 }}>{segments.map((segment) => { const extracted = selectedWorkspace?.extractedSegmentIds?.includes(segment.id); const result = selectedWorkspace?.segmentResults?.find((item) => item.segmentId === segment.id); return <div key={segment.id} style={{ display: "flex", alignItems: "center", gap: 6, padding: "6px 0", borderTop: "0.5px solid rgba(0,0,0,.06)", fontSize: 10 }}><span style={{ flex: 1 }}>#{segment.sequence} · {new Date(segment.started_at).toLocaleString()} · {segment.message_count} 条 · {extracted ? `${result?.experienceCount || 0} 条经历 / ${result?.noteCount || 0} 条 MD 素材` : "未提取"}</span><button style={button} disabled={!!busy} onClick={() => extractOne(segment)}>{busy === segment.id ? "提取中…" : extracted ? "重新提取" : "提取"}</button></div>; })}</div></>}
    {selectedWorkspace && <Workspace workspace={selectedWorkspace} documents={documents} busy={busy === selectedWorkspace.id || selectedWorkspace.notes.some((note) => note.id === busy) || selectedWorkspace.patches.some((patch) => patch.id === busy)} onAssign={assign} onDistill={distill} onMerge={merge} onPatchReview={reviewPatch} />}
    <BatchDetails batches={selectedBatches} />
  </div>;
}
