import { useEffect, useRef, useState } from "react";
import { api } from "./api.js";

const button={border:0,borderRadius:12,padding:"6px 10px",fontSize:10.5,cursor:"pointer"};
const field={width:"100%",boxSizing:"border-box",border:"0.5px solid rgba(0,0,0,.1)",borderRadius:8,padding:7,fontFamily:"inherit",fontSize:10.5,marginTop:5};
function CandidateEditor({candidate,busy,onReview,onSaved}){
  const [draft,setDraft]=useState(candidate); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
  async function save(){try{setSaving(true);setMessage("");const d=await api(`/timeline-candidates/${candidate.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:draft.title,bodyMarkdown:draft.body_markdown,currentState:draft.current_state,indexSummary:draft.index_summary,evidenceQuotes:draft.evidence_quotes,evidenceTerms:draft.evidence_terms})});setDraft(d.candidate);onSaved(d.candidate);setMessage("修改已保存。");return d.candidate}catch(e){setMessage(e.message);return null}finally{setSaving(false)}}
  async function confirm(){const saved=await save();if(saved)onReview(saved,"confirm")}
  return <article style={{padding:"10px",margin:"8px 0",border:"0.5px solid rgba(0,0,0,.08)",borderRadius:12,background:"rgba(0,0,0,.015)"}}>
    <label style={{fontSize:9.5,color:"#8E8E93"}}>日记标题</label><input style={field} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/>
    <label style={{fontSize:9.5,color:"#8E8E93"}}>Markdown 正文</label><textarea rows={5} style={field} value={draft.body_markdown} onChange={e=>setDraft({...draft,body_markdown:e.target.value})}/>
    <label style={{fontSize:9.5,color:"#8E8E93"}}>片段结束时的状态</label><input style={field} value={draft.current_state} onChange={e=>setDraft({...draft,current_state:e.target.value})}/>
    <label style={{fontSize:9.5,color:"#8E8E93"}}>检索摘要</label><input style={field} value={draft.index_summary} onChange={e=>setDraft({...draft,index_summary:e.target.value})}/>
    <p style={{fontSize:10,color:"#8E8E93"}}><b>证据原话：</b>{(draft.evidence_quotes||[]).join(" / ")}</p>
    {message&&<p style={{fontSize:10,color:message.includes("保存")?"#34C759":"#FF3B30"}}>{message}</p>}
    <button style={button} disabled={saving||busy} onClick={save}>{saving?"保存中…":"保存修改"}</button><button style={{...button,background:"#1C1C1E",color:"white"}} disabled={saving||busy} onClick={confirm}>确认进入正式日记</button><button style={{...button,color:"#FF3B30",background:"transparent"}} disabled={busy} onClick={()=>onReview(draft,"reject")}>拒绝</button>
  </article>;
}

export default function TimelineImportSettings({mode="import",onCandidateGenerated}){
  const input=useRef(null); const [imports,setImports]=useState([]); const [segments,setSegments]=useState([]);
  const [candidates,setCandidates]=useState([]); const [preview,setPreview]=useState(null); const [busy,setBusy]=useState(""); const [message,setMessage]=useState("");
  const refreshCandidates=()=>api("/timeline-candidates").then(d=>setCandidates((d.candidates||[]).filter(x=>x.status==="suggested")));
  useEffect(()=>{if(mode==="import")api("/timeline-imports").then(d=>setImports(d.imports||[])).catch(e=>setMessage(e.message));refreshCandidates().catch(e=>setMessage(e.message));},[mode]);
  async function upload(event){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(file.size>1500000)return setMessage("文件不能超过 1.5MB。");try{setBusy("upload");const exportData=JSON.parse(await file.text());const d=await api("/timeline-imports",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({sourceFilename:file.name,exportData})});setImports(x=>[d.import,...x]);setSegments((d.segments||[]).map(s=>({...s,candidateCount:0,suggestedCount:0})));setMessage(`导入成功：${d.import.message_count} 条消息，分成 ${d.import.segment_count} 个片段。尚未发送给记忆模型。`)}catch(e){setMessage(e.message)}finally{setBusy("")}}
  async function openImport(item){try{const d=await api(`/timeline-imports/${item.id}/segments`);setSegments(d.segments||[]);setPreview(null);setMessage("")}catch(e){setMessage(e.message)}}
  async function show(segment){try{const d=await api(`/timeline-segments/${segment.id}`);setPreview(d.segment)}catch(e){setMessage(e.message)}}
  async function generate(segment){try{setBusy(segment.id);setMessage("正在生成候选日记…");const d=await api(`/timeline-segments/${segment.id}/generate`,{method:"POST"});setCandidates(x=>[...(d.candidates||[]),...x.filter(c=>c.segment_id!==segment.id)]);setSegments(x=>x.map(s=>s.id===segment.id?{...s,status:"generated",candidateCount:d.candidateCount,suggestedCount:d.candidateCount}:s));if(d.candidateCount===0){setMessage("生成完成：AI 判断这个片段没有值得长期记录的内容。请结合原文判断是否合理。")}else{setMessage(`生成完成：得到 ${d.candidateCount} 条候选，正在打开“待审核”。`);onCandidateGenerated?.(d.candidateCount)}return d.candidateCount}catch(e){setMessage(e.message);return null}finally{setBusy("")}}
  async function generateTestBatch(){const pending=segments.filter(s=>s.status==="pending").slice(0,10);if(!pending.length)return setMessage("没有待处理片段。");if(!window.confirm(`将依次调用记忆 API 处理 ${pending.length} 个片段，继续吗？`))return;for(const segment of pending)await generate(segment);setMessage(`测试批次完成，请进入“待审核”查看结果。`);onCandidateGenerated?.()}
  async function review(candidate,action){try{setBusy(candidate.id);await api(`/timeline-candidates/${candidate.id}/${action}`,{method:"POST"});setCandidates(x=>x.filter(c=>c.id!==candidate.id));setMessage(action==="confirm"?"已加入正式 Markdown 日记。":"已拒绝，不会进入正式日记。")}catch(e){setMessage(e.message)}finally{setBusy("")}}

  if(mode==="review")return <div><p style={{fontSize:10.5,color:"#8E8E93"}}>这里保存所有尚未确认的候选。重新打开设置也不会消失。</p>{message&&<p style={{fontSize:10.5,color:"#8E8E93"}}>{message}</p>}{!candidates.length&&<p style={{fontSize:10.5,color:"#8E8E93"}}>目前没有待审核内容。</p>}{candidates.map(c=><CandidateEditor key={c.id} candidate={c} busy={busy===c.id} onReview={review} onSaved={saved=>setCandidates(x=>x.map(v=>v.id===saved.id?saved:v))}/>)}</div>;

  return <div><p style={{fontSize:10.5,color:"#8E8E93"}}>导入只是日记的原料入口。点击“生成候选”才会把该片段发送给独立记忆模型。</p><button type="button" style={button} disabled={busy==="upload"} onClick={()=>input.current?.click()}>{busy==="upload"?"解析中…":"上传 Claude JSON"}</button><input ref={input} hidden type="file" accept=".json,application/json" onChange={upload}/>{message&&<p role="status" style={{fontSize:10.5,color:message.includes("不能")?"#FF3B30":"#8E8E93",whiteSpace:"pre-wrap"}}>{message}</p>}{imports.map(item=><button key={item.id} type="button" onClick={()=>openImport(item)} style={{...button,display:"block",width:"100%",textAlign:"left",marginTop:6}}>{item.title} · {item.message_count} 条 · {item.segment_count} 段</button>)}{!!segments.length&&<><button type="button" style={{...button,marginTop:8}} disabled={!!busy} onClick={generateTestBatch}>测试前 10 个待处理片段</button><div style={{marginTop:8,maxHeight:240,overflowY:"auto"}}>{segments.map(s=>{const state=s.status==="pending"?"未处理":s.candidateCount===0?"已处理 · 没有候选":s.suggestedCount>0?`待审核 ${s.suggestedCount} 条`:`已处理 · ${s.candidateCount||0} 条`;return <div key={s.id} style={{display:"flex",gap:5,alignItems:"center",padding:"6px 0",borderTop:"0.5px solid rgba(0,0,0,.05)",fontSize:10}}><span style={{flex:1}}>#{s.sequence} · {new Date(s.started_at).toLocaleString()} · {s.message_count}条<br/><b>{state}</b></span><button style={button} onClick={()=>show(s)}>原文</button><button style={button} disabled={busy===s.id} onClick={()=>generate(s)}>{busy===s.id?"生成中…":s.status==="pending"?"生成候选":"重新生成"}</button></div>})}</div></>}{preview&&<details open style={{marginTop:8}}><summary style={{fontSize:10.5}}>片段原文预览</summary><pre style={{whiteSpace:"pre-wrap",maxHeight:260,overflow:"auto",fontSize:9.5,background:"rgba(0,0,0,.025)",padding:8,borderRadius:8}}>{preview.cleaned_transcript}</pre></details>}</div>;
}
